import {
  MdAdd,
  MdFavorite,
  MdHome,
  MdLibraryMusic,
  MdSearch,
  MdPlayCircleFilled,
  MdPauseCircleFilled,
  MdSkipPrevious,
  MdSkipNext,
  MdVolumeDown,
  MdSignalWifiConnectedNoInternet4,
  MdShuffle,
  MdRepeat,
} from 'react-icons/md'

export const Icons = {
  Add: MdAdd,
  Favorite: MdFavorite,
  Home: MdHome,
  LibraryMusic: MdLibraryMusic,
  Search: MdSearch,
  PlayCircleFilled: MdPlayCircleFilled,
  PauseCircleFilled: MdPauseCircleFilled,
  SkipPrevious: MdSkipPrevious,
  SkipNext: MdSkipNext,
  Speaker: MdVolumeDown,
  NoInternet: MdSignalWifiConnectedNoInternet4,
  Shuffle: MdShuffle,
  Repeat: MdRepeat,
}
